Marvinschirrmacher
FH-Bielefeld-MIF-SW-Engineering-2017/Script pull request #103
Opened 2017-06-05 11:29 UTC by MarvinSchirrmacher

Zusammenfassungen der Kapitel 7 und 8 des Buchs ‚Enterprise Architecture At Work‘

2017-06-05 13:20 UTC, smaier1 requested changes
Bitte einmal die aktuelle Version von Github holen und dann noch einmal ein Pullrequest senden.
Was sollen die beiden Dateien "softskills...." sein sind das Reste oder hast du deine alten Zusammenfassugen überarbeitet. Ich kann sie bei Github nicht finden.

2017-06-05 13:26 UTC, MarvinSchirrmacher commented
Hi, mein GitHub sagt, dass es aktuell ist :



Ja, ich habe mir den aktuellen Master von Remote geholt und gesehen, dass ich manche Korrekturen damals wohl vergessen habe zu committen.

> Am 05.06.2017 um 15:20 schrieb smaier1 <notifications@github.com>:
> 
> @smaier1 requested changes on this pull request.
> 
> Bitte einmal die aktuelle Version von Github holen und dann noch einmal ein Pullrequest senden.
> Was sollen die beiden Dateien "softskills...." sein sind das Reste oder hast du deine alten Zusammenfassugen überarbeitet. Ich kann sie bei Github nicht finden.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/FH-Bielefeld-MIF-SW-Engineering-2017/Script/pull/103#pullrequestreview-42041610>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ACYj-cGtWKi4R80IX5t5U4kV0raobrEyks5sBAC0gaJpZM4Nv7dg>.
>

2017-06-05 13:33 UTC, smaier1 requested changes
Dann entferne bitte noch die beiden Dateien soft_skills/2_marketing_yourself.marvin.md
soft_skills.2_marketing_yourself.marvin.md
oder lösche die beiden Commits und sende noch einmal einen Pullrequest.

2017-06-05 14:03 UTC, MarvinSchirrmacher commented
Ok, gelöscht und commitet. Den Pull Request hier also schließen und einen neuen machen?

2017-06-06 15:35 UTC, smaier1 approved these changes

2017-06-06 15:35 UTC, merged