Aguenter
FH-Bielefeld-MIF-SW-Engineering-2017/Script pull request #106
Opened 2017-06-05 13:00 UTC by aguenter

Abgabe Zusammenfassung: Enterprise Architecture at Work

Ich werde Ende dieser Woche einen weiteren Pull Request stellen und kleine Verbesserungen an meiner vorigen Abgabe vornehmen. Das habe ich mit Prof. Brunsmann so abgesprochen, größtenteils sind das Veränderungen des Ausdrucks und Korrekturen von Rechtschreibfehlern.

2017-06-05 13:28 UTC, smaier1 requested changes
Einige Überschriften müssen angepasst werden, da sie nicht als Überschriften im Moment definiert sind (nach der Raute müsste eigentlich noch ein Leerzeichen kommen).
Die Bildunterschriften fehlen, so dass im Text nicht klar ist auf welches Bild gerade verwiesen wird. In der Readmedatei steht, wie es richtig geht.

2017-06-11 15:33 UTC, aguenter commented
Habe die Änderungen eingepflegt.

2017-06-11 19:15 UTC, aguenter commented
Die Gliederung für die morgige Abgabe ist jetzt auch mit drin.

2017-06-12 13:13 UTC, aguenter commented
Konflikte sind gelöst.

2017-06-12 13:13 UTC, merged